### ISSUE TITLE
https://appuio.ch/javascripts/jquerylbslider.js missing

### ISSUE THREAD

**Issue by igrcic** [appuio/website#181]
Hi,

it seems that the following library is missing when accessing the appuio.ch site:

Request URL: https://appuio.ch/javascripts/jquerylbslider.js
Request Method: GET
Status Code: 404 Not Found

We have noticed that because the sitecheck on https://sitecheck.sucuri.net/results/appuio.ch was complaining about (blacklisting in mcaffee) the appuio website.

Kind regards,
Ivan

**Comment by lbischof** [comment]
This has been fixed by the new website
